//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicAnchors.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicAnchors.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IyBCbGVuZGVyIHYyLjkyLjAgT0JKIEZpbGU6ICdhbmNob3JzX21vZGVscy5ibGVuZCcNCiMgd3d3LmJsZW5kZXIub3JnDQp2IDkuNTAwMDAwIC01NC43NTAwMDQgMC4wMDAwMDANCnYgOS41MDAwMDAgLTU0Ljc1MDAwNCAxNTAuMDAwMDAwDQp2IDkuNTAwMDAwIDU0Ljc1MDAwNCAwLjAwMDAwMA0KdiA5LjUwMDAwMCA1NC43NTAwMDQgMTUwLjAwMDAwMA0KdiAxNS41MDAwMDAgLTU0Ljc1MDAwNCAwLjAwMDAwMA0KdiAxNS41MDAwMDAgLTU0Ljc1MDAwNCAxNTAuMDAwMDAwDQp2IDE1LjUwMDAwMCA1NC43NTAwMDQgMC4wMDAwMDANCnYgMTUuNTAwMDAwIDU0Ljc1MDAwNCAxNTAuMDAwMDAwDQp2IC0xNS41MDAwMDAgLTU0Ljc1MDAwNCAwLjAwMDAwMA0KdiAtMTUuNTAwMDAwIC01 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string tas_4_0 {
            get {
                return ResourceManager.GetString("tas-4.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IyBCbGVuZGVyIHYyLjkyLjAgT0JKIEZpbGU6ICdhbmNob3JzX21vZGVscy5ibGVuZCcNCiMgd3d3LmJsZW5kZXIub3JnDQp2IDkuNTAwMDAwIC01NC43NTAwMDQgMC4wMDAwMDANCnYgOS41MDAwMDAgLTU0Ljc1MDAwNCAxNTAuMDAwMDAwDQp2IDkuNTAwMDAwIDU0Ljc1MDAwNCAwLjAwMDAwMA0KdiA5LjUwMDAwMCA1NC43NTAwMDQgMTUwLjAwMDAwMA0KdiAxNS41MDAwMDAgLTU0Ljc1MDAwNCAwLjAwMDAwMA0KdiAxNS41MDAwMDAgLTU0Ljc1MDAwNCAxNTAuMDAwMDAwDQp2IDE1LjUwMDAwMCA1NC43NTAwMDQgMC4wMDAwMDANCnYgMTUuNTAwMDAwIDU0Ljc1MDAwNCAxNTAuMDAwMDAwDQp2IC0xNS41MDAwMDAgLTU0Ljc1MDAwNCAwLjAwMDAwMA0KdiAtMTUuNTAwMDAwIC01 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string tas_4_5 {
            get {
                return ResourceManager.GetString("tas-4.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IyBCbGVuZGVyIHYyLjkyLjAgT0JKIEZpbGU6ICdhbmNob3JzX21vZGVscy5ibGVuZCcNCiMgd3d3LmJsZW5kZXIub3JnDQp2IDkuNTAwMDAwIC01NC43NTAwMDQgMC4wMDAwMDANCnYgOS41MDAwMDAgLTU0Ljc1MDAwNCAxNTAuMDAwMDAwDQp2IDkuNTAwMDAwIDU0Ljc1MDAwNCAwLjAwMDAwMA0KdiA5LjUwMDAwMCA1NC43NTAwMDQgMTUwLjAwMDAwMA0KdiAxNS41MDAwMDAgLTU0Ljc1MDAwNCAwLjAwMDAwMA0KdiAxNS41MDAwMDAgLTU0Ljc1MDAwNCAxNTAuMDAwMDAwDQp2IDE1LjUwMDAwMCA1NC43NTAwMDQgMC4wMDAwMDANCnYgMTUuNTAwMDAwIDU0Ljc1MDAwNCAxNTAuMDAwMDAwDQp2IC0xNS41MDAwMDAgLTU0Ljc1MDAwNCAwLjAwMDAwMA0KdiAtMTUuNTAwMDAwIC01 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string tas_5_0 {
            get {
                return ResourceManager.GetString("tas-5.0", resourceCulture);
            }
        }
    }
}
