//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicMasts.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicMasts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на diAtMjUwLjAwMDAwMCAwLjAwMDAwMCAwLjAwMDAwMA0KdiAtMjUwLjAwMDAwMCAwLjAwMDAwMCAxMDAwMC4wMDAwMDANCnYgLTI0NS4xOTYzMjAgNDguNzcyNTc5IDAuMDAwMDAwDQp2IC0yNDUuMTk2MzIwIDQ4Ljc3MjU3OSAxMDAwMC4wMDAwMDANCnYgLTIzMC45Njk4NzkgOTUuNjcwODYwIDAuMDAwMDAwDQp2IC0yMzAuOTY5ODc5IDk1LjY3MDg2MCAxMDAwMC4wMDAwMDANCnYgLTIwNy44Njc0MDEgMTM4Ljg5MjU2MyAwLjAwMDAwMA0KdiAtMjA3Ljg2NzQwMSAxMzguODkyNTYzIDEwMDAwLjAwMDAwMA0KdiAtMTc2Ljc3NjY4OCAxNzYuNzc2Njg4IDAuMDAwMDAwDQp2IC0xNzYuNzc2Njg4IDE3Ni43NzY2ODggMTAwMDAuMDAwMDAwDQp2IC0xMzguODkyNTQ4IDIwNy44Njc0 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string a_10 {
            get {
                return ResourceManager.GetString("a_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на diAtMjUwLjAwMDAwMCAwLjAwMDAwMCAwLjAwMDAwMA0KdiAtMjUwLjAwMDAwMCAwLjAwMDAwMCAxMjAwMC4wMDAwMDANCnYgLTI0NS4xOTYzMjAgNDguNzcyNTc5IDAuMDAwMDAwDQp2IC0yNDUuMTk2MzIwIDQ4Ljc3MjU3OSAxMjAwMC4wMDAwMDANCnYgLTIzMC45Njk4NzkgOTUuNjcwODYwIDAuMDAwMDAwDQp2IC0yMzAuOTY5ODc5IDk1LjY3MDg2MCAxMjAwMC4wMDAwMDANCnYgLTIwNy44Njc0MDEgMTM4Ljg5MjU2MyAwLjAwMDAwMA0KdiAtMjA3Ljg2NzQwMSAxMzguODkyNTYzIDEyMDAwLjAwMDAwMA0KdiAtMTc2Ljc3NjY4OCAxNzYuNzc2Njg4IDAuMDAwMDAwDQp2IC0xNzYuNzc2Njg4IDE3Ni43NzY2ODggMTIwMDAuMDAwMDAwDQp2IC0xMzguODkyNTQ4IDIwNy44Njc0 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string a_12 {
            get {
                return ResourceManager.GetString("a_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на diAtMjUwLjAwMDAwMCAwLjAwMDAwMCAwLjAwMDAwMA0KdiAtMjUwLjAwMDAwMCAwLjAwMDAwMCAxNTAwMC4wMDAwMDANCnYgLTI0NS4xOTYzMjAgNDguNzcyNTc5IDAuMDAwMDAwDQp2IC0yNDUuMTk2MzIwIDQ4Ljc3MjU3OSAxNTAwMC4wMDAwMDANCnYgLTIzMC45Njk4NzkgOTUuNjcwODYwIDAuMDAwMDAwDQp2IC0yMzAuOTY5ODc5IDk1LjY3MDg2MCAxNTAwMC4wMDAwMDANCnYgLTIwNy44Njc0MDEgMTM4Ljg5MjU2MyAwLjAwMDAwMA0KdiAtMjA3Ljg2NzQwMSAxMzguODkyNTYzIDE1MDAwLjAwMDAwMA0KdiAtMTc2Ljc3NjY4OCAxNzYuNzc2Njg4IDAuMDAwMDAwDQp2IC0xNzYuNzc2Njg4IDE3Ni43NzY2ODggMTUwMDAuMDAwMDAwDQp2IC0xMzguODkyNTQ4IDIwNy44Njc0 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string a_15 {
            get {
                return ResourceManager.GetString("a_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IyBCbGVuZGVyIHYyLjkwLjEgT0JKIEZpbGU6ICfQnNCfLmJsZW5kJw0KIyB3d3cuYmxlbmRlci5vcmcNCnYgLTEwOC42MzMwMDMgMTY4LjkyODM5MSA4Mzk5Ljg0NzY1Ng0KdiAtMTA4LjYzMzAwMyAxNjguOTI4MzkxIDgyNzkuODQ3NjU2DQp2IC0xMDguNjMzMDAzIC0xNzEuMDc1ODIxIDgyNzkuODQ3NjU2DQp2IC0xMDguNjMzMDAzIC0xNzEuMDc1ODIxIDgzOTkuODQ3NjU2DQp2IC0xMDguNjMzMDAzIC0yNzEuMDc0NzY4IDcwNTkuODQ2NjgwDQp2IC0xMDguNjMzMDAzIC0xNzEuMDc1ODIxIDg5MTkuODQ3NjU2DQp2IC0xMDguNjMzMDAzIC0xNzEuMDc1ODIxIDkwMzkuODQ3NjU2DQp2IC0xMDguNjMzMDAzIDE2OC45MjgzOTEgOTAzOS44NDc2NTYNCnYgLTEwOC42MzMwMDMg [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string m_10 {
            get {
                return ResourceManager.GetString("m_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IyBCbGVuZGVyIHYyLjkwLjEgT0JKIEZpbGU6ICfQnNCfLmJsZW5kJw0KIyB3d3cuYmxlbmRlci5vcmcNCnYgLTEyOS44MTE5OTYgMzIxLjY1MjQwNSA3My43NTAwMTUNCnYgLTEwOS45OTkwMDEgMjcwLjAwMTQwNCA5NjE5LjcxMDkzOA0KdiAtMTA5Ljk5OTAwMSAxNzAuMDAzNDE4IDc3NTkuNzQ1NjA1DQp2IC0xMDkuOTk5MDAxIDE3MC4wMDM0MTggODI3OS43NDUxMTcNCnYgLTEwOS45OTkwMDEgMTcwLjAwMzQxOCA3NjM5Ljc0NDYyOQ0KdiAtMTA5Ljk5OTAwMSAtMTY5Ljk5MzYzNyA3NjM5Ljc0MzY1Mg0KdiAtMTA5Ljk5OTAwMSAtMTY5Ljk5MzYzNyA3NzU5Ljc0MzY1Mg0KdiAtMTA5Ljk5OTAwMSAtMjY5Ljk5NTY5NyA5NjE5LjcxMDkzOA0KdiAtMTA5Ljk5OTAwMSAtMTY5 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string m_12 {
            get {
                return ResourceManager.GetString("m_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IyBCbGVuZGVyIHYyLjkwLjEgT0JKIEZpbGU6ICfQnNCfLmJsZW5kJw0KIyB3d3cuYmxlbmRlci5vcmcNCnYgLTEwOS45MzYwMDUgMTY5Ljk4OTAxNCA3NDM5Ljk0Mjg3MQ0KdiAtMTA5LjkzNzAwNCAxNjkuOTg5MDE0IDc1NTkuOTQyODcxDQp2IC0xMDkuOTM2MDA1IDI2OS45ODcwMzAgNzQ5OS45NDI4NzENCnYgMTEwLjA2Mjk5NiAxNjkuOTkwMDA1IDEwNjM5LjgyNzE0OA0KdiAxMTAuMDYyOTk2IDE2OS45OTAwMDUgMTA3NTkuODI3MTQ4DQp2IDExMC4wNjI5OTYgLTE3MC4wMTE5OTMgMTA3NTkuODI2MTcyDQp2IDExMC4wNjI5OTYgLTE3MC4wMTE5OTMgMTA2MzkuODI1MTk1DQp2IDExMC4wNjI5OTYgLTI3MC4wMTE5OTMgMTI2MTkuNzkxOTkyDQp2IDExMC4wNjI5OTYgLTE3 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string m_15 {
            get {
                return ResourceManager.GetString("m_15", resourceCulture);
            }
        }
    }
}
