//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicMasts.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicMasts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на diAtMjUwLjAwMDAwMCAwLjAwMDAwMCAwLjAwMDAwMA0KdiAtMjUwLjAwMDAwMCAwLjAwMDAwMCAxMDAwMC4wMDAwMDANCnYgLTI0NS4xOTYzMjAgNDguNzcyNTc5IDAuMDAwMDAwDQp2IC0yNDUuMTk2MzIwIDQ4Ljc3MjU3OSAxMDAwMC4wMDAwMDANCnYgLTIzMC45Njk4NzkgOTUuNjcwODYwIDAuMDAwMDAwDQp2IC0yMzAuOTY5ODc5IDk1LjY3MDg2MCAxMDAwMC4wMDAwMDANCnYgLTIwNy44Njc0MDEgMTM4Ljg5MjU2MyAwLjAwMDAwMA0KdiAtMjA3Ljg2NzQwMSAxMzguODkyNTYzIDEwMDAwLjAwMDAwMA0KdiAtMTc2Ljc3NjY4OCAxNzYuNzc2Njg4IDAuMDAwMDAwDQp2IC0xNzYuNzc2Njg4IDE3Ni43NzY2ODggMTAwMDAuMDAwMDAwDQp2IC0xMzguODkyNTQ4IDIwNy44Njc0 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string a_10 {
            get {
                return ResourceManager.GetString("a_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на diAtMjUwLjAwMDAwMCAwLjAwMDAwMCAwLjAwMDAwMA0KdiAtMjUwLjAwMDAwMCAwLjAwMDAwMCAxMjAwMC4wMDAwMDANCnYgLTI0NS4xOTYzMjAgNDguNzcyNTc5IDAuMDAwMDAwDQp2IC0yNDUuMTk2MzIwIDQ4Ljc3MjU3OSAxMjAwMC4wMDAwMDANCnYgLTIzMC45Njk4NzkgOTUuNjcwODYwIDAuMDAwMDAwDQp2IC0yMzAuOTY5ODc5IDk1LjY3MDg2MCAxMjAwMC4wMDAwMDANCnYgLTIwNy44Njc0MDEgMTM4Ljg5MjU2MyAwLjAwMDAwMA0KdiAtMjA3Ljg2NzQwMSAxMzguODkyNTYzIDEyMDAwLjAwMDAwMA0KdiAtMTc2Ljc3NjY4OCAxNzYuNzc2Njg4IDAuMDAwMDAwDQp2IC0xNzYuNzc2Njg4IDE3Ni43NzY2ODggMTIwMDAuMDAwMDAwDQp2IC0xMzguODkyNTQ4IDIwNy44Njc0 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string a_12 {
            get {
                return ResourceManager.GetString("a_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на diAtMjUwLjAwMDAwMCAwLjAwMDAwMCAwLjAwMDAwMA0KdiAtMjUwLjAwMDAwMCAwLjAwMDAwMCAxNTAwMC4wMDAwMDANCnYgLTI0NS4xOTYzMjAgNDguNzcyNTc5IDAuMDAwMDAwDQp2IC0yNDUuMTk2MzIwIDQ4Ljc3MjU3OSAxNTAwMC4wMDAwMDANCnYgLTIzMC45Njk4NzkgOTUuNjcwODYwIDAuMDAwMDAwDQp2IC0yMzAuOTY5ODc5IDk1LjY3MDg2MCAxNTAwMC4wMDAwMDANCnYgLTIwNy44Njc0MDEgMTM4Ljg5MjU2MyAwLjAwMDAwMA0KdiAtMjA3Ljg2NzQwMSAxMzguODkyNTYzIDE1MDAwLjAwMDAwMA0KdiAtMTc2Ljc3NjY4OCAxNzYuNzc2Njg4IDAuMDAwMDAwDQp2IC0xNzYuNzc2Njg4IDE3Ni43NzY2ODggMTUwMDAuMDAwMDAwDQp2IC0xMzguODkyNTQ4IDIwNy44Njc0 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string a_15 {
            get {
                return ResourceManager.GetString("a_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на diAyNTAuMDAwMDAwIC0yNTAuMDAwMDAwIDAuMDAwMDAwDQp2IDI1MC4wMDAwMDAgLTI1MC4wMDAwMDAgMTAwMDAuMDAwMDAwDQp2IC0yNTAuMDAwMDAwIC0yNTAuMDAwMDAwIDAuMDAwMDAwDQp2IC0yNTAuMDAwMDAwIC0yNTAuMDAwMDAwIDEwMDAwLjAwMDAwMA0KdiAyNTAuMDAwMDAwIDI1MC4wMDAwMDAgMC4wMDAwMDANCnYgMjUwLjAwMDAwMCAyNTAuMDAwMDAwIDEwMDAwLjAwMDAwMA0KdiAtMjUwLjAwMDAwMCAyNTAuMDAwMDAwIDAuMDAwMDAwDQp2IC0yNTAuMDAwMDAwIDI1MC4wMDAwMDAgMTAwMDAuMDAwMDAwDQp2biAwLjAwMDAgLTEuMDAwMCAwLjAwMDANCnZuIC0xLjAwMDAgMC4wMDAwIDAuMDAwMA0Kdm4gMC4wMDAwIDEuMDAwMCAwLjAwMDANCnZuIDEuMDAwMCAw [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string m_10 {
            get {
                return ResourceManager.GetString("m_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на diAyNTAuMDAwMDAwIC0yNTAuMDAwMDAwIDAuMDAwMDAwDQp2IDI1MC4wMDAwMDAgLTI1MC4wMDAwMDAgMTIwMDAuMDAwMDAwDQp2IC0yNTAuMDAwMDAwIC0yNTAuMDAwMDAwIDAuMDAwMDAwDQp2IC0yNTAuMDAwMDAwIC0yNTAuMDAwMDAwIDEyMDAwLjAwMDAwMA0KdiAyNTAuMDAwMDAwIDI1MC4wMDAwMDAgMC4wMDAwMDANCnYgMjUwLjAwMDAwMCAyNTAuMDAwMDAwIDEyMDAwLjAwMDAwMA0KdiAtMjUwLjAwMDAwMCAyNTAuMDAwMDAwIDAuMDAwMDAwDQp2IC0yNTAuMDAwMDAwIDI1MC4wMDAwMDAgMTIwMDAuMDAwMDAwDQp2biAwLjAwMDAgLTEuMDAwMCAwLjAwMDANCnZuIC0xLjAwMDAgMC4wMDAwIDAuMDAwMA0Kdm4gMC4wMDAwIDEuMDAwMCAwLjAwMDANCnZuIDEuMDAwMCAw [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string m_12 {
            get {
                return ResourceManager.GetString("m_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на diAyNTAuMDAwMDAwIC0yNTAuMDAwMDAwIDAuMDAwMDAwDQp2IDI1MC4wMDAwMDAgLTI1MC4wMDAwMDAgMTUwMDAuMDAwMDAwDQp2IC0yNTAuMDAwMDAwIC0yNTAuMDAwMDAwIDAuMDAwMDAwDQp2IC0yNTAuMDAwMDAwIC0yNTAuMDAwMDAwIDE1MDAwLjAwMDAwMA0KdiAyNTAuMDAwMDAwIDI1MC4wMDAwMDAgMC4wMDAwMDANCnYgMjUwLjAwMDAwMCAyNTAuMDAwMDAwIDE1MDAwLjAwMDAwMA0KdiAtMjUwLjAwMDAwMCAyNTAuMDAwMDAwIDAuMDAwMDAwDQp2IC0yNTAuMDAwMDAwIDI1MC4wMDAwMDAgMTUwMDAuMDAwMDAwDQp2biAwLjAwMDAgLTEuMDAwMCAwLjAwMDANCnZuIC0xLjAwMDAgMC4wMDAwIDAuMDAwMA0Kdm4gMC4wMDAwIDEuMDAwMCAwLjAwMDANCnZuIDEuMDAwMCAw [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string m_15 {
            get {
                return ResourceManager.GetString("m_15", resourceCulture);
            }
        }
    }
}
