//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicFoundations.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicFoundations.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на diAzNTAuMDAwMDAwIC0zNTAuMDAwMDAwIDAuMDAwMDAwDQp2IDM1MC4wMDAwMDAgLTM1MC4wMDAwMDAgLTQwMDAuMDAwMDAwDQp2IC0zNTAuMDAwMDAwIC0zNTAuMDAwMDAwIDAuMDAwMDAwDQp2IC0zNTAuMDAwMDAwIC0zNTAuMDAwMDAwIC00MDAwLjAwMDAwMA0KdiAzNTAuMDAwMDAwIDM1MC4wMDAwMDAgMC4wMDAwMDANCnYgMzUwLjAwMDAwMCAzNTAuMDAwMDAwIC00MDAwLjAwMDAwMA0KdiAtMzUwLjAwMDAwMCAzNTAuMDAwMDAwIDAuMDAwMDAwDQp2IC0zNTAuMDAwMDAwIDM1MC4wMDAwMDAgLTQwMDAuMDAwMDAwDQpmIDUgMyAxDQpmIDMgOCA0DQpmIDcgNiA4DQpmIDIgOCA2DQpmIDEgNCAyDQpmIDUgMiA2DQpmIDUgNyAzDQpmIDMgNyA4DQpmIDcgNSA2DQpmIDIgNCA4 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string direct {
            get {
                return ResourceManager.GetString("direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на diAtMC4wMDAwMTkgMTY0Ljk5OTk1NCAtODgwLjAwMDI0NA0KdiAzMi4xODk4ODQgMTYxLjgyOTUyOSAtODgwLjAwMDI0NA0KdiA2My4xNDI3NTQgMTUyLjQ0MDA2MyAtODgwLjAwMDI0NA0KdiA5MS42NjkwNzUgMTM3LjE5MjQ0NCAtODgwLjAwMDI0NA0KdiAxMTYuNjcyNjAwIDExNi42NzI1NjkgLTg4MC4wMDAyNDQNCnYgMTM3LjE5MjQ3NCA5MS42NjkwMzcgLTg4MC4wMDAyNDQNCnYgMTUyLjQ0MDA5NCA2My4xNDI3MTUgLTg4MC4wMDAyNDQNCnYgMTYxLjgyOTU1OSAzMi4xODk4NjEgLTg4MC4wMDAyNDQNCnYgMTYxLjgyOTU1OSAtMzIuMTg5OTM4IC04ODAuMDAwMjQ0DQp2IDE1Mi40NDAxMDkgLTYzLjE0Mjc5MiAtODgwLjAwMDI0NA0KdiAxMzcuMTkyNDc0IC05MS42Njkx [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string tss_4_0 {
            get {
                return ResourceManager.GetString("tss-4.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на diAtMC4wMDAwMTkgMTY0Ljk5OTk1NCAtODgwLjAwMDI0NA0KdiAzMi4xODk4ODQgMTYxLjgyOTUyOSAtODgwLjAwMDI0NA0KdiA2My4xNDI3NTQgMTUyLjQ0MDA2MyAtODgwLjAwMDI0NA0KdiA5MS42NjkwNzUgMTM3LjE5MjQ0NCAtODgwLjAwMDI0NA0KdiAxMTYuNjcyNjAwIDExNi42NzI1NjkgLTg4MC4wMDAyNDQNCnYgMTM3LjE5MjQ3NCA5MS42NjkwMzcgLTg4MC4wMDAyNDQNCnYgMTUyLjQ0MDA5NCA2My4xNDI3MTUgLTg4MC4wMDAyNDQNCnYgMTYxLjgyOTU1OSAzMi4xODk4NjEgLTg4MC4wMDAyNDQNCnYgMTYxLjgyOTU1OSAtMzIuMTg5OTM4IC04ODAuMDAwMjQ0DQp2IDE1Mi40NDAxMDkgLTYzLjE0Mjc5MiAtODgwLjAwMDI0NA0KdiAxMzcuMTkyNDc0IC05MS42Njkx [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string tss_4_5 {
            get {
                return ResourceManager.GetString("tss-4.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на diAtMC4wMDAwMTkgMTY0Ljk5OTk1NCAtODgwLjAwMDI0NA0KdiAzMi4xODk4ODQgMTYxLjgyOTUyOSAtODgwLjAwMDI0NA0KdiA2My4xNDI3NTQgMTUyLjQ0MDA2MyAtODgwLjAwMDI0NA0KdiA5MS42NjkwNzUgMTM3LjE5MjQ0NCAtODgwLjAwMDI0NA0KdiAxMTYuNjcyNjAwIDExNi42NzI1NjkgLTg4MC4wMDAyNDQNCnYgMTM3LjE5MjQ3NCA5MS42NjkwMzcgLTg4MC4wMDAyNDQNCnYgMTUyLjQ0MDA5NCA2My4xNDI3MTUgLTg4MC4wMDAyNDQNCnYgMTYxLjgyOTU1OSAzMi4xODk4NjEgLTg4MC4wMDAyNDQNCnYgMTYxLjgyOTU1OSAtMzIuMTg5OTM4IC04ODAuMDAwMjQ0DQp2IDE1Mi40NDAxMDkgLTYzLjE0Mjc5MiAtODgwLjAwMDI0NA0KdiAxMzcuMTkyNDc0IC05MS42Njkx [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string tss_5_0 {
            get {
                return ResourceManager.GetString("tss-5.0", resourceCulture);
            }
        }
    }
}
