//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicBasements.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicBasements.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IyBCbGVuZGVyIHYyLjkwLjEgT0JKIEZpbGU6ICfQotCh0J8uYmxlbmQnDQojIHd3dy5ibGVuZGVyLm9yZw0KdiAyNjcuNzg1NDkyIC0yMjkuNjAxOTkwIDEwMy40NTc5ODUNCnYgMjg0LjI4ODQ4MyAtMjAxLjAyMjk5NSAyMS4xNDY5ODINCnYgMjg0LjI4ODQ4MyAtMjAxLjAyMjk5NSAxMDMuNDU3OTg1DQp2IC0yMzIuMTg3NTAwIDIyNy42MzA5OTcgMTAzLjQ1Nzk4NQ0KdiAtMjY1LjE4NDQ3OSAyMjcuNjMwOTk3IDIxLjE0Njk4Mg0KdiAtMjY1LjE4NDQ3OSAyMjcuNjMwOTk3IDEwMy40NTc5ODUNCnYgMjY5LjM2MTUxMSAxOTkuMDUyMDAyIC0wLjYxMDYyMA0KdiAyNjAuMzI3NDg0IDIxNC42OTUwMDcgMTMyLjI1NTk5Nw0KdiAyNjAuMzI3NDg0IDIxNC42OTUwMDcgLTAuNjEw [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TSP4_5 {
            get {
                return ResourceManager.GetString("TSP4.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IyBCbGVuZGVyIHYyLjkwLjEgT0JKIEZpbGU6ICfQotCh0J8uYmxlbmQnDQojIHd3dy5ibGVuZGVyLm9yZw0KdiAyNjcuNzg1NDkyIC0yMjkuNjAxOTkwIDEwMy40NTc5ODUNCnYgMjg0LjI4ODQ4MyAtMjAxLjAyMjk5NSAyMS4xNDY5ODINCnYgMjg0LjI4ODQ4MyAtMjAxLjAyMjk5NSAxMDMuNDU3OTg1DQp2IC0yMzIuMTg3NTAwIDIyNy42MzA5OTcgMTAzLjQ1Nzk4NQ0KdiAtMjY1LjE4NDQ3OSAyMjcuNjMwOTk3IDIxLjE0Njk4Mg0KdiAtMjY1LjE4NDQ3OSAyMjcuNjMwOTk3IDEwMy40NTc5ODUNCnYgMjY5LjM2MTUxMSAxOTkuMDUyMDAyIC0wLjYxMDYyMA0KdiAyNjAuMzI3NDg0IDIxNC42OTUwMDcgMTMyLjI1NTk5Nw0KdiAyNjAuMzI3NDg0IDIxNC42OTUwMDcgLTAuNjEw [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TSP5_0 {
            get {
                return ResourceManager.GetString("TSP5.0", resourceCulture);
            }
        }
    }
}
