//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicMasts.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicMasts.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IyBCbGVuZGVyIHYyLjgzLjAgT0JKIEZpbGU6ICdtLmJsZW5kJw0KIyB3d3cuYmxlbmRlci5vcmcNCnYgLTYwMC4wMDAwMDAgMC4wMDAwMDAgMC4wMDAwMDANCnYgLTYwMC4wMDAwMDAgMC4wMDAwMDAgMjAwMDAuMDAwMDAwDQp2IC01ODguNDcxMTMwIDExNy4wNTQxOTIgMC4wMDAwMDANCnYgLTU4OC40NzExMzAgMTE3LjA1NDE5MiAyMDAwMC4wMDAwMDANCnYgLTU1NC4zMjc2OTggMjI5LjYxMDA3NyAwLjAwMDAwMA0KdiAtNTU0LjMyNzY5OCAyMjkuNjEwMDc3IDIwMDAwLjAwMDAwMA0KdiAtNDk4Ljg4MTc0NCAzMzMuMzQyMTMzIDAuMDAwMDAwDQp2IC00OTguODgxNzQ0IDMzMy4zNDIxMzMgMjAwMDAuMDAwMDAwDQp2IC00MjQuMjY0MDY5IDQyNC4yNjQwNjkgMC4wMDAwMDAN [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string a_10 {
            get {
                return ResourceManager.GetString("a_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IyBCbGVuZGVyIHYyLjgzLjAgT0JKIEZpbGU6ICdtLmJsZW5kJw0KIyB3d3cuYmxlbmRlci5vcmcNCnYgLTYwMC4wMDAwMDAgMC4wMDAwMDAgMC4wMDAwMDANCnYgLTYwMC4wMDAwMDAgMC4wMDAwMDAgMjQwMDAuMDAwMDAwDQp2IC01ODguNDcxMTMwIDExNy4wNTQxOTIgMC4wMDAwMDANCnYgLTU4OC40NzExMzAgMTE3LjA1NDE5MiAyNDAwMC4wMDAwMDANCnYgLTU1NC4zMjc2OTggMjI5LjYxMDA3NyAwLjAwMDAwMA0KdiAtNTU0LjMyNzY5OCAyMjkuNjEwMDc3IDI0MDAwLjAwMDAwMA0KdiAtNDk4Ljg4MTc0NCAzMzMuMzQyMTMzIDAuMDAwMDAwDQp2IC00OTguODgxNzQ0IDMzMy4zNDIxMzMgMjQwMDAuMDAwMDAwDQp2IC00MjQuMjY0MDY5IDQyNC4yNjQwNjkgMC4wMDAwMDAN [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string a_12 {
            get {
                return ResourceManager.GetString("a_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IyBCbGVuZGVyIHYyLjgzLjAgT0JKIEZpbGU6ICdtLmJsZW5kJw0KIyB3d3cuYmxlbmRlci5vcmcNCnYgLTYwMC4wMDAwMDAgMC4wMDAwMDAgMC4wMDAwMDANCnYgLTYwMC4wMDAwMDAgMC4wMDAwMDAgMzAwMDAuMDAwMDAwDQp2IC01ODguNDcxMTMwIDExNy4wNTQxOTIgMC4wMDAwMDANCnYgLTU4OC40NzExMzAgMTE3LjA1NDE5MiAzMDAwMC4wMDAwMDANCnYgLTU1NC4zMjc2OTggMjI5LjYxMDA3NyAwLjAwMDAwMA0KdiAtNTU0LjMyNzY5OCAyMjkuNjEwMDc3IDMwMDAwLjAwMDAwMA0KdiAtNDk4Ljg4MTc0NCAzMzMuMzQyMTMzIDAuMDAwMDAwDQp2IC00OTguODgxNzQ0IDMzMy4zNDIxMzMgMzAwMDAuMDAwMDAwDQp2IC00MjQuMjY0MDY5IDQyNC4yNjQwNjkgMC4wMDAwMDAN [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string a_15 {
            get {
                return ResourceManager.GetString("a_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IyBCbGVuZGVyIHYyLjgzLjAgT0JKIEZpbGU6ICdtLmJsZW5kJw0KIyB3d3cuYmxlbmRlci5vcmcNCnYgLTYwMC4wMDAwMDAgNjAwLjAwMDAwMCAyMDAwMC4wMDAwMDANCnYgLTYwMC4wMDAwMDAgNjAwLjAwMDAwMCAwLjAwMDAwMA0KdiA2MDAuMDAwMDAwIDYwMC4wMDAwMDAgMjAwMDAuMDAwMDAwDQp2IDYwMC4wMDAwMDAgNjAwLjAwMDAwMCAwLjAwMDAwMA0KdiAtNjAwLjAwMDAwMCAtNjAwLjAwMDAwMCAyMDAwMC4wMDAwMDANCnYgLTYwMC4wMDAwMDAgLTYwMC4wMDAwMDAgMC4wMDAwMDANCnYgNjAwLjAwMDAwMCAtNjAwLjAwMDAwMCAyMDAwMC4wMDAwMDANCnYgNjAwLjAwMDAwMCAtNjAwLjAwMDAwMCAwLjAwMDAwMA0KcyBvZmYNCmYgMSA1IDcgMw0KZiA0IDMgNyA4DQpm [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string m_10 {
            get {
                return ResourceManager.GetString("m_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IyBCbGVuZGVyIHYyLjgzLjAgT0JKIEZpbGU6ICdtLmJsZW5kJw0KIyB3d3cuYmxlbmRlci5vcmcNCnYgLTYwMC4wMDAwMDAgNjAwLjAwMDAwMCAyNDAwMC4wMDAwMDANCnYgLTYwMC4wMDAwMDAgNjAwLjAwMDAwMCAwLjAwMDAwMA0KdiA2MDAuMDAwMDAwIDYwMC4wMDAwMDAgMjQwMDAuMDAwMDAwDQp2IDYwMC4wMDAwMDAgNjAwLjAwMDAwMCAwLjAwMDAwMA0KdiAtNjAwLjAwMDAwMCAtNjAwLjAwMDAwMCAyNDAwMC4wMDAwMDANCnYgLTYwMC4wMDAwMDAgLTYwMC4wMDAwMDAgMC4wMDAwMDANCnYgNjAwLjAwMDAwMCAtNjAwLjAwMDAwMCAyNDAwMC4wMDAwMDANCnYgNjAwLjAwMDAwMCAtNjAwLjAwMDAwMCAwLjAwMDAwMA0KcyBvZmYNCmYgMSA1IDcgMw0KZiA0IDMgNyA4DQpm [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string m_12 {
            get {
                return ResourceManager.GetString("m_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IyBCbGVuZGVyIHYyLjgzLjAgT0JKIEZpbGU6ICdtLmJsZW5kJw0KIyB3d3cuYmxlbmRlci5vcmcNCnYgLTYwMC4wMDAwMDAgNjAwLjAwMDAwMCAzMDAwMC4wMDAwMDANCnYgLTYwMC4wMDAwMDAgNjAwLjAwMDAwMCAwLjAwMDAwMA0KdiA2MDAuMDAwMDAwIDYwMC4wMDAwMDAgMzAwMDAuMDAwMDAwDQp2IDYwMC4wMDAwMDAgNjAwLjAwMDAwMCAwLjAwMDAwMA0KdiAtNjAwLjAwMDAwMCAtNjAwLjAwMDAwMCAzMDAwMC4wMDAwMDANCnYgLTYwMC4wMDAwMDAgLTYwMC4wMDAwMDAgMC4wMDAwMDANCnYgNjAwLjAwMDAwMCAtNjAwLjAwMDAwMCAzMDAwMC4wMDAwMDANCnYgNjAwLjAwMDAwMCAtNjAwLjAwMDAwMCAwLjAwMDAwMA0KcyBvZmYNCmYgMSA1IDcgMw0KZiA0IDMgNyA4DQpm [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string m_15 {
            get {
                return ResourceManager.GetString("m_15", resourceCulture);
            }
        }
    }
}
