name: DocFX

on:
  - push
  - pull_request

jobs:
  docfx_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: ./Docs/docfx.json

    - uses: peaceiris/actions-gh-pages@v3
      name: Deploy to GitHub Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Docs/docs
        allow_empty_commit: true
        enable_jekyll: true
        cname: catenary.nagikh.com
